### ISSUE TITLE
Who has write access to this repo?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-org/committee#6]
It would be good to know who on the committee has write access to this repo. I haven't, and as far as I can tell from the autocomplete suggestions @TikhonJelvis does but @rebeccaskinner doesn't.

**Comment by TikhonJelvis** [comment]
Everyone in the **haskell-org** group can edit the repo. @rebeccaskinner is in the group but has her membership set to "private", so she doesn't get autocompleted.

I forgot to add you when you joined the committee. Just sent you an invite; once you accept, you should have write access to the repo.
