### ISSUE TITLE
Create a policy for www.haskell.org repo access

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-org/committee#9]
In the committee meeting we drafted the following policy for www.haskell.org repo access. The maintainers should be

* Each member of the commiteee
* Members of the haskell-infra team
* Others that the committee appoints by vote from time to time

**Comment by dschrempf** [comment]
I think this can be closed because #11 has been merged. Is that so?

**Comment by tomjaguarpaw** [comment]
Yes, thanks!
